name: Feeds
attributes:
  ORGANIZATIONNAME: Daniel Moro
  #CLASSPREFIX: Ez
targets:
  FeedsCore:
    sources: Sources/Core
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: 10.15
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: 10.15
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
    info:
        path: Sources/Core/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
    scheme:
      testTargets:
        - FeedsTests
      gatherCoverageData: true
  Prototype:
    sources: Sources/Prototype
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 13
    info:
      path: Sources/Prototype/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSupportsIndirectInputEvents: true
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        PRODUCT_BUNDLE_IDENTIFIER: com.Moroverse.FeedsPrototype
        #DEVELOPMENT_TEAM: 3Q2494254L
        MARKETING_VERSION: 0.1
        CURRENT_PROJECT_VERSION: 0.1.0
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  FeedsTests:
    sources:
      - path: Tests/Isolated
        group: Tests
      - path: Tests/Helpers
        group: Tests
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: FeedsCore
    settings:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    info:
        path: Tests/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  FeedsIntegrationTests:
    sources:
      - path: Tests/Integration
        group: Tests
      - path: Tests/Helpers
        group: Tests
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: FeedsCore
    settings:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    info:
        path: Tests/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
schemes:
  CI:
    build:
      targets:
        FeedsCore: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - FeedsCore
      targets:
        - name: FeedsTests
          randomExecutionOrder: true
        - name: FeedsIntegrationTests
          randomExecutionOrder: true
