name: Feeds
targets:
  Feeds:
    sources: Sources
    type: framework
    platform: macOS
    info:
        path: Sources/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  FeedsTests:
    sources: Tests
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: Feeds
    info:
        path: Tests/Info.plist
