name: Feeds
attributes:
  ORGANIZATIONNAME: Daniel Moro
  #CLASSPREFIX: Ez
targets:
  FeedsCore:
    sources: Sources/Core
    type: framework
    platform: macOS
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: 10.15
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos macosx
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
    info:
        path: Sources/Core/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
    scheme:
      testTargets:
        - FeedsTests
      gatherCoverageData: true
  FeedsTests:
    sources:
      - path: Tests/Core/Isolated
        group: Tests
      - path: Tests/Helpers
        group: Tests
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: FeedsCore
    settings:
      MACOSX_DEPLOYMENT_TARGET: 10.15
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      SUPPORTED_PLATFORMS: iphonesimulator iphoneos macosx
    info:
        path: Tests/Core/Isolated/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  FeedsIntegrationTests:
    sources:
      - path: Tests/Core/Integration
        group: Tests
      - path: Tests/Helpers
        group: Tests
    type: bundle.unit-test
    platform: macOS
    dependencies:
      - target: FeedsCore
    settings:
      MACOSX_DEPLOYMENT_TARGET: 10.15
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      SUPPORTED_PLATFORMS: iphonesimulator iphoneos macosx
    info:
        path: Tests/Core/Integration/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  Feeds_iOS:
    sources: Sources/iOS
    type: framework
    platform: iOS
    dependencies:
      - target: FeedsCore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: Apple Development
    info:
        path: Sources/iOS/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
    scheme:
      testTargets:
        - Feeds_iOSTests
      gatherCoverageData: true
  Feeds_iOSTests:
    sources:
      - path: Tests/iOS
        group: Tests
      - path: Tests/Helpers
        group: Tests
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: FeedsCore
      - target: Feeds_iOS
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
    info:
        path: Tests/iOS/Info.plist
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
  Prototype:
    sources: Sources/Prototype
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 13
    info:
      path: Sources/Prototype/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneStoryboardFile: Main
        UIApplicationSupportsIndirectInputEvents: true
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        PRODUCT_BUNDLE_IDENTIFIER: com.Moroverse.FeedsPrototype
        #DEVELOPMENT_TEAM: 3Q2494254L
        MARKETING_VERSION: 0.1
        CURRENT_PROJECT_VERSION: 0.1.0
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
    prebuildScripts:
      - script: |
                swiftformat --swiftversion 5.3 .
                swiftlint autocorrrect
                swiftlint lint
        name: Build Tools
schemes:
  CI_macOS:
    build:
      targets:
        FeedsCore: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - FeedsCore
      targets:
        - name: FeedsTests
          randomExecutionOrder: true
        - name: FeedsIntegrationTests
          randomExecutionOrder: true
  CI_iOS:
    build:
      targets:
        FeedsCore: all
        Feeds_iOS: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - FeedsCore
        - Feeds_iOS
      targets:
        - name: FeedsTests
          randomExecutionOrder: true
        - name: FeedsIntegrationTests
          randomExecutionOrder: true
        - name: Feeds_iOSTests
          randomExecutionOrder: true
