name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: xavierLowmiller/xcodegen-action@1.0.0
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Build and test macOS
      run: xcodebuild clean build test -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    - name: Build and test iOS
      run: xcodebuild clean build test -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
